### ISSUE TITLE
window.supertokensUIMultitenancy is undefined

### ISSUE THREAD

**Issue by victorlevasseur** [supertokens/prebuiltui#2]
Hi,

I would like to apply the multi tenant flow explained here : 
https://supertokens.com/docs/passwordless/common-customizations/multi-tenancy/common-domain-login

But it seems window.supertokensUIMultitenancy is undefined in the prebuilt ui, not allowing me to use it.

**Comment by rishabhpoddar** [comment]
Thanks for the issue. This has been fixed in this bundle: `https://cdn.jsdelivr.net/gh/supertokens/prebuiltui@v0.47.0/build/static/js/main.8f01ace8.js`.

Please feel free to reopen this issue if still seeing the error
